updated postman folder ref with other repo

diff --git a/.github/workflows/run-postman.yml b/.github/workflows/run-postman.yml
--- a/.github/workflows/run-postman.yml
+++ b/.github/workflows/run-postman.yml
@@ -116,4 +116,8 @@ jobs:
               --env-var "username=$username" \
               --env-var "password=$password" \
               --env-var "baseUrl=$base_url"
+            if [ $? -ne 0 ]; then
+              echo "Postman collection failed: $postman_file"
+              exit 1
+            fi
           done
